/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * sh_comparison_property
 */
export class ComparisonPropertyInfo {
    createTime?: string;
    createUser?: string;
    deleteFlag?: boolean;
    essential?: boolean;
    id?: string;
    shAnalyseId?: string;
    shComparisonId?: string;
    shPropertyId?: string;
    shVersionId?: string;
    updateTime?: string;
    updateUser?: string;
}

