/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComparisonMemberInfo } from './comparisonMemberInfo';

export class ComparisonFeeInfo {
    auAvg?: number;
    auBalanceI?: number;
    auTransactions?: number;
    bondAvg?: number;
    bondBalanceI?: number;
    bondTransactions?: number;
    chooseAu?: boolean;
    chooseBond?: boolean;
    chooseIntl?: boolean;
    chooseMa?: boolean;
    chooseMf?: boolean;
    chooseRetIns?: boolean;
    comparisonId?: string;
    createTime?: string;
    createUser?: string;
    deleteFlag?: boolean;
    holdingsNumber?: number;
    id?: string;
    idpsCashBalance?: number;
    idpsNumRetIns?: number;
    intlAvg?: number;
    intlBalanceI?: number;
    intlTransactions?: number;
    maAuAvg?: number;
    maAuTransactions?: number;
    maBalanceI?: number;
    maIntlAvg?: number;
    maIntlTransactions?: number;
    maMfAvg?: number;
    maMfTransactions?: number;
    members?: Array<ComparisonMemberInfo> = new Array<ComparisonMemberInfo>();
    mfAvg?: number;
    mfBalanceI?: number;
    mfTransactions?: number;
    premiumAvg?: number;
    superCashBalance?: number;
    superNumRetIns?: number;
    updateTime?: string;
    updateUser?: string;
}

