/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComparisonMemberValueInfo } from './comparisonMemberValueInfo';


export class ComparisonMemberInfo {
    comparisonFeeId?: string;
    comparisonId?: string;
    createTime?: string;
    createUser?: string;
    deleteFlag?: boolean;
    id?: string;
    memberValues?: Array<ComparisonMemberValueInfo> = new Array<ComparisonMemberValueInfo>();
    name?: string;
    updateTime?: string;
    updateUser?: string;
}

