/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ComparisonMemberValueInfo {
    balance?: number;
    comparisonFeeId?: string;
    comparisonId?: string;
    createTime?: string;
    createUser?: string;
    deleteFlag?: boolean;
    id?: string;
    memberId?: string;
    name?: string;
    type?: string; // IDPS、Super
    updateTime?: string;
    updateUser?: string;
}

