/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {Attachment} from "../attachment";

/**
 * sh_practice表
 */
export class PracticeInfo {
    abn?: string;
    address?: string;
    afslNum?: string;
    attachmentVo?: Attachment = new Attachment();
    billingDate?: Date | string;
    createTime?: string;
    createUser?: string;
    deleteFlag?: boolean;
    domain?: string;
    archiveFlag?: boolean;
    id?: string;
    name?: string;
    signDate?: Date | string;
    /**
     * Normal,Disable
     */
    status?: string;
    updateTime?: string;
    updateUser?: string;
    totalUser?: number;
    totalAdviser?: number;
}

