/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {Attachment} from "../attachment";
import {BaseModel} from "./baseModel";

/**
 * sh_product表
 */
export class ProductInfo extends BaseModel{
    archived?: boolean; // 是否归档
    companyId?: string;
    companyName?: string; // supplierName
    attachmentId?: string;
    platformLogo?: Attachment = new Attachment();
    attachmentVo?: Attachment = new Attachment();
    description?: string;
    name?: string;
    platformName?: string;
    status?: string;
    versionId?: string;
    workflowStatus?: number; // 1: Data required, 2: Awaiting approval, 3: Awaiting publish

}

