/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * sh_product_prop表
 */
export class ProductPropInfo {
    attachmentId?: string;
    createTime?: string;
    createUser?: string;
    deleteFlag?: boolean;
    description?: string;
    id?: string;
    propValue?: string;
    shProductId?: string;
    shPropertyId?: string;
    updateTime?: string;
    updateUser?: string;
}

