/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {Attachment} from "../attachment";
import {BaseModel} from "./baseModel";
import FinalAnalyse from "./finalAnalyse";
import {ComparisonCommentInfo} from "./comparisonCommentInfo";
import {Product} from "./feeReviewChart";

/**
 * sh_product_prop表
 */
export class ProductPropInfo extends BaseModel{
    attachmentId?: string;
    attachmentVo?: Attachment = new Attachment();
    attachment?: Attachment = new Attachment();
    description?: string;
    propValue?: string;
    shProductId?: string;
    shPropertyId?: string;
    bmFlag?: boolean;
    freezeFieldName?: string;
    moveFlag?: boolean;
    prodPropDesc?: string;
    prodPropId?: string;
    propDesc?: string;
    propName?: string;
    status?: string; // Normal,Insert,Update,Archive
    tabType?: string;
    type?: string;
    versionId?: string;
    vsFlag?: boolean;
    productName?: string;
    matchPercent?: number;
    productPropVoList?: Array<ProductPropInfo> = new Array<ProductPropInfo>();
    comments: Array<ComparisonCommentInfo> = new Array<ComparisonCommentInfo>();
    finalAnalyse: FinalAnalyse = new FinalAnalyse();
    products: Array<Product> = new Array<Product>(); // fee charts product data
}

