/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {Attachment} from "../attachment";

/**
 * sh_supplier表
 */
export class SupplierInfo {
    archiveFlag?: boolean;
    attachmentVo?: Attachment;
    contactEmail?: string;
    contactName?: string;
    contactNum?: string;
    createTime?: string;
    createUser?: string;
    deleteFlag?: boolean;
    description?: string;
    id?: string;
    name?: string;
    /**
     * Active,Disable
     */
    status?: string;
    updateTime?: string;
    updateUser?: string;
    website?: string;
    totalUser?: number;
    totalBdm?: number;
    totalPremium?: number;
}

