/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * sh_supplier_public_details表
 */
export class SupplierPublicDetailInfo {
    biography?: string;
    contactEmail?: string;
    contactHours?: string;
    contactNum?: string;
    createTime?: string;
    createUser?: string;
    deleteFlag?: boolean;
    id?: string;
    linkedUrl?: string;
    region?: string;
    shSupplierId?: string;
    updateTime?: string;
    updateUser?: string;
    userId?: string;
}
