/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * sh_supplier_user_product表
 */
export class SupplierUserProductInfo {
    createTime?: string;
    createUser?: string;
    deleteFlag?: boolean;
    id?: string;
    shProductId?: string;
    shSupplierId?: string;
    updateTime?: string;
    updateUser?: string;
    userId?: string;
}
