/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {RoleInfo} from "./roleInfo";
import {Attachment} from "../attachment";

/**
 * sh_team表
 */
export class TeamInfo {
    arn?: string;
    attachmentVo?: Attachment = new Attachment();
    createTime?: string;
    createUser?: string;
    deleteFlag?: boolean;
    email?: string;
    firstName?: string;
    id?: string;
    lastName?: string;
    loginTime?: string;
    practiceId?: string;
    practiceRoleId?: string;
    practiceRoleName?: string;
    practiceRoleVos?: Array<RoleInfo>;
    roleId?: string;
    openId?: string;
    roleInfos?: Array<RoleInfo>;
    roleName?: string;
    /**
     * Active,Pending,Disable
     */
    status?: string;
    updateTime?: string;
    updateUser?: string;
    userId?: string;
}

