/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {BaseModel} from "./baseModel";

/**
 * 版本信息表
 */
export class Version extends BaseModel{
    productId?: string;
    /**
     * Publish,Draft,History
     */
    type?: string;
    version?: string;
    versionStatus?: string;
    modelVersionId?: string;
    shProductId?: string;
    publishPlatformFlag?: boolean;
    username?: string;
}
