/**
 * Suitability Hub
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {ComparisonProductInfo} from "../po/comparisonProductInfo";
import {Attachment} from "../attachment";
import {ProductPropInfo} from "../po/productPropInfo";
import {ComparisonCommentInfo} from "../po/comparisonCommentInfo";

/**
 * sh_comparison_product
 */
export class ComparisonProductVo extends ComparisonProductInfo{
    checked: boolean = true;
    essential: boolean = true;
    attachmentVo?: Attachment;
    productPropVoList?: Array<ProductPropInfo> = new Array<ProductPropInfo>();
    comparisonComment: ComparisonCommentInfo;
}

